### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by tihmstar** [neal/savethemblobs#1]
Im getting this error after executing:
./savethemblobs.py 0000000000000 iPhone4,1

Submitting blobs to Cydia server
Traceback (most recent call last):
  File "./savethemblobs.py", line 173, in <module>
    main(sys.argv[1:])
  File "./savethemblobs.py", line 124, in main
    submit_blobs_to_cydia(cpid, bdid, ecid, blobs)
  File "./savethemblobs.py", line 66, in submit_blobs_to_cydia
    return r.text
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 809, in text
    content = str(self.content, encoding, errors='replace')
TypeError: unicode() argument 2 must be string, not None

**Comment by tihmstar** [comment]
Solved, by modifying line 66 to " return r.status_code"
