### ISSUE TITLE
iOS 10.3.1 Saving

### ISSUE THREAD

**Issue by conorswee** [neal/savethemblobs#8]
Has errors when saving blobs for the iPhone5,2, iPhone5,3, and iPhone5,4. Have not tested any other devices

**Comment by OothecaPickle** [comment]
@csweeney29 I'm experiencing the same issue. Until this issue is fixed, just use [tsschecker](https://github.com/tihmstar/tsschecker) as it can now save blobs without a nonce as well.

**Comment by HackintoshHD** [comment]
Same here for an iPhone5,2 and an iPhone9,3, here's the terminal output (relevant parameters anonymized):

```./savethemblobs.py --save-dir /Volumes/Macintosh\ SSD/Users/MyUserName/Documents/SHSH\ Blobs/My\ iPhone\ 7/ --no-submit-cydia 0xECID iPhone9,3
Fetching firmwares Apple is currently signing for iPhone9,3
Requesting blobs from Apple for iPhone9,3/14E304
Traceback (most recent call last):
  File "./savethemblobs.py", line 195, in <module>
    sys.exit(main())
  File "./savethemblobs.py", line 128, in main
    r = request_blobs_from_apple(board, f['build'], ecid, cpid, bdid)
  File "./savethemblobs.py", line 51, in request_blobs_from_apple
    r = requests.post(url, headers={'User-Agent': USER_AGENT}, data=tss_request_manifest(board, build, ecid, cpid, bdid))
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/Library/Python/2.7/site-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 31: ordinal not in range(128)```

**Comment by HackintoshHD** [comment]
For future reference, this _could_ be the same issue as issue #6 .

**Comment by HackintoshHD** [comment]
Further info: No problems with an iPad3,6. Up to this point, only iPhones seem to be affected.
