### ISSUE TITLE
Linux platform not supported?

### ISSUE THREAD

**Issue by Qwertylex** [neal/savethemblobs#9]
> python2 ./savefromdevice.py 
Traceback (most recent call last):
  File "./savefromdevice.py", line 8, in <module>
    from MobileDevice import *
  File "/home/alex/iphone/savethemblobs/MobileDevice/__init__.py", line 29, in <module>
    from afc import *
  File "/home/alex/iphone/savethemblobs/MobileDevice/afc.py", line 25, in <module>
    from MobileDevice import *
  File "/home/alex/iphone/savethemblobs/MobileDevice/MobileDevice.py", line 28, in <module>
    from CoreFoundation import *
  File "/home/alex/iphone/savethemblobs/MobileDevice/CoreFoundation.py", line 35, in <module>
    raise OSError(u'Platform not supported')
OSError: Platform not supported
>
Arch Linux 4.10.9-1-ARCH #1 SMP PREEMPT Sat Apr 8 12:39:59 CEST 2017 x86_64 GNU/Linux
Server = https://archive.archlinux.org/repos/2017/04/15/$repo/os/$arch
(arch linux is pinned to 2017-04-15)

**Comment by toniqyteza** [comment]
You need to install pip and python
